# Generated by Django 5.2.9 on 2026-01-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seqcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='seq name')),
                ('fichier', models.FileField(upload_to='equipes/docs/')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seqcol', to='users.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tablecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='table name')),
                ('fichier', models.FileField(upload_to='equipes/docs/')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablecor', to='users.equipe')),
            ],
        ),
    ]
