# Generated by Django 5.2.9 on 2026-01-17 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_equipe_usermodel_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='equipes',
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejoint', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_rejoint'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes_membres', through='users.MembreEquipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
