# Generated by Django 5.2.9 on 2026-01-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_equipe_usermodel_equipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='isAdministrator',
            field=models.BooleanField(default=False),
        ),
    ]
