# Generated by Django 5.2.9 on 2026-02-04 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seqcollection_is_validated_seqcollection_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
