# Generated by Django 5.2.9 on 2026-01-15 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plasmide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plasmide')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('accession', models.CharField(blank=True, max_length=50, verbose_name='Accession')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('genbank_definition', models.CharField(blank=True, max_length=255, verbose_name='Definition GenBank')),
                ('organism', models.CharField(blank=True, max_length=150, verbose_name='Organisme')),
                ('mol_type', models.CharField(blank=True, max_length=50, verbose_name='Type molécule')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés')),
                ('reference_authors', models.TextField(blank=True, verbose_name='Auteurs / Référence')),
                ('reference_journal', models.TextField(blank=True, verbose_name='Journal / Citation')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Longueur (bp)')),
                ('sequence', models.TextField(blank=True, verbose_name='Séquence (nt)')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Features (brut)')),
                ('gc_content', models.FloatField(blank=True, null=True, verbose_name='GC (%)')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='campaign_templates/', verbose_name='Fichier Excel')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name="Nom d'affichage")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='campaign_templates/', verbose_name='Fichier Excel')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name="Nom d'affichage")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plasmides', models.ManyToManyField(blank=True, related_name='campaigns', to='gestionTemplate.plasmide')),
            ],
        ),
    ]
