# Generated by Django 6.0.1 on 2026-01-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restriction_enzyme', models.CharField(choices=[('BsaI', 'BsaI'), ('BsmBI', 'BsmBI'), ('BbsI', 'BbsI'), ('SapI', 'SapI')], default='BsaI', max_length=10)),
                ('separator_sortie', models.CharField(default='-', max_length=10)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_names', models.CharField(max_length=100)),
                ('part_types', models.CharField(blank=True, max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('in_output_name', models.BooleanField(default=True)),
                ('part_separators', models.CharField(blank=True, max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='gestionTemplate.campaigntemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du fichier de correspondance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mapping_file', models.FileField(help_text='Fichier CSV/Excel original de correspondance', upload_to='user_mapping_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la table de correspondance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mapping', models.JSONField(default=dict, verbose_name='Mapping')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
                ('mapping_template', models.OneToOneField(blank=True, help_text='Fichier original associé à cette table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondance_table', to='gestionTemplate.mappingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Plasmide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plasmide')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dossier', models.CharField(default=None, verbose_name='dossier pour regrouper les plasmides')),
                ('accession', models.CharField(blank=True, max_length=50, verbose_name='Accession')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('genbank_definition', models.CharField(blank=True, max_length=255, verbose_name='Definition GenBank')),
                ('organism', models.CharField(blank=True, max_length=150, verbose_name='Organisme')),
                ('mol_type', models.CharField(blank=True, max_length=50, verbose_name='Type molécule')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés')),
                ('reference_authors', models.TextField(blank=True, verbose_name='Auteurs / Référence')),
                ('reference_journal', models.TextField(blank=True, verbose_name='Journal / Citation')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Longueur (bp)')),
                ('sequence', models.TextField(blank=True, verbose_name='Séquence (nt)')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Features (brut)')),
                ('gc_content', models.FloatField(blank=True, null=True, verbose_name='GC (%)')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlasmidCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la collection')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('plasmid_archive', models.FileField(help_text='Archive ZIP contenant les fichiers .gb originaux', upload_to='user_plasmid_collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasmid_collections', to=settings.AUTH_USER_MODEL)),
                ('plasmides', models.ManyToManyField(blank=True, help_text='Plasmides parsés depuis cette collection', related_name='collections', to='gestionTemplate.plasmide')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_file', models.FileField(null=True, upload_to='simulations/templates/')),
                ('mapping_file', models.FileField(null=True, upload_to='simulations/mappings/')),
                ('plasmid_archive', models.FileField(null=True, upload_to='simulations/plasmid_archive/')),
                ('primers_file', models.FileField(blank=True, null=True, upload_to='simulations/primers/')),
                ('concentration_file', models.FileField(blank=True, null=True, upload_to='simulations/concentrations/')),
                ('enzyme', models.CharField(blank=True, max_length=100, null=True)),
                ('default_concentration', models.FloatField(default=200.0)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='simulations/results/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mapping_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='gestionTemplate.mappingtemplate')),
                ('plasmid_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='gestionTemplate.plasmidcollection')),
                ('plasmids', models.ManyToManyField(blank=True, to='gestionTemplate.plasmide')),
            ],
        ),
    ]
