# Generated by Django 5.2.9 on 2026-01-13 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=36)),
                ('template_file', models.FileField(upload_to='anonymous_templates/')),
                ('mapping_file', models.FileField(upload_to='anonymous_templates/')),
                ('plasmids_zip', models.FileField(upload_to='anonymous_templates/')),
                ('primers_file', models.FileField(blank=True, null=True, upload_to='anonymous_templates/')),
                ('concentration_file', models.FileField(blank=True, null=True, upload_to='anonymous_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='concentration_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_templates/'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='mapping_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_templates/'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='plasmids_zip',
            field=models.FileField(blank=True, null=True, upload_to='campaign_templates/'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='primers_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_templates/'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
