# Generated by Django 5.2.9 on 2026-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmide',
            name='dossier',
            field=models.CharField(default='public', max_length=255, verbose_name='dossier pour regrouper les plasmides'),
        ),
        migrations.AlterUniqueTogether(
            name='plasmide',
            unique_together={('name', 'dossier')},
        ),
    ]
