# Generated by Django 5.2.9 on 2026-01-27 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestionTemplate", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.equipe",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaigntemplate",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.equipe",
            ),
        ),
        migrations.AddField(
            model_name="campaigntemplate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="columntemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="gestionTemplate.campaigntemplate",
            ),
        ),
        migrations.AddField(
            model_name="correspondancetable",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.equipe",
            ),
        ),
        migrations.AddField(
            model_name="mappingtemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondancetable",
            name="mapping_template",
            field=models.OneToOneField(
                blank=True,
                help_text="Fichier original associé à cette table",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondance_table",
                to="gestionTemplate.mappingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="mapping_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="gestionTemplate.mappingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="plasmidcollection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plasmid_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="plasmid_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="gestionTemplate.plasmidcollection",
            ),
        ),
        migrations.AddField(
            model_name="plasmide",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.equipe",
            ),
        ),
        migrations.AddField(
            model_name="plasmide",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plasmidcollection",
            name="plasmides",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plasmides parsés depuis cette collection",
                related_name="collections",
                to="gestionTemplate.plasmide",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="plasmids",
            field=models.ManyToManyField(blank=True, to="gestionTemplate.plasmide"),
        ),
    ]
