# Generated by Django 5.2.9 on 2026-01-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='file',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='plasmides',
        ),
        migrations.AddField(
            model_name='campaign',
            name='concentration_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/concentrations/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_concentration',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enzyme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mapping_file',
            field=models.FileField(default=0, upload_to='simulations/mappings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='plasmids_archive',
            field=models.FileField(default=0, upload_to='simulations/plasmids/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='primers_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/primers/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/results/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_file',
            field=models.FileField(default=0, upload_to='simulations/templates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
