# Generated by Django 5.2.9 on 2026-01-20 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0001_initial'),
        ('users', '0003_usermodel_isadministrator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='file',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='plasmides',
        ),
        migrations.AddField(
            model_name='campaign',
            name='concentration_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/concentrations/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_concentration',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enzyme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mapping_file',
            field=models.FileField(null=True, upload_to='simulations/mappings/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='plasmids',
            field=models.ManyToManyField(blank=True, to='gestionTemplate.plasmide'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='primers_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/primers/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/results/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_file',
            field=models.FileField(null=True, upload_to='simulations/templates/'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe'),
        ),
        migrations.AddField(
            model_name='plasmide',
            name='dossier',
            field=models.CharField(default=None, verbose_name='dossier pour regrouper les plasmides'),
        ),
        migrations.AddField(
            model_name='plasmide',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe'),
        ),
        migrations.AddField(
            model_name='plasmide',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorrespondanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la table de correspondance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mapping', models.JSONField(default=dict, verbose_name='Mapping')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe')),
            ],
        ),
    ]
