# Generated by Django 5.2.9 on 2026-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0002_alter_plasmide_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmide',
            name='dossier',
            field=models.CharField(default='public', max_length=255, verbose_name='Dossier'),
        ),
    ]
