# Generated by Django 5.2.9 on 2026-01-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionTemplate", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du fichier de correspondance"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "mapping_file",
                    models.FileField(
                        help_text="Fichier CSV/Excel original de correspondance",
                        upload_to="user_mapping_templates/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="mapping_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="gestionTemplate.mappingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="correspondancetable",
            name="mapping_template",
            field=models.OneToOneField(
                blank=True,
                help_text="Fichier original associé à cette table",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondance_table",
                to="gestionTemplate.mappingtemplate",
            ),
        ),
        migrations.CreateModel(
            name="PlasmidCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la collection"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "plasmid_archive",
                    models.FileField(
                        help_text="Archive ZIP contenant les fichiers .gb originaux",
                        upload_to="user_plasmid_collections/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plasmides",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plasmides parsés depuis cette collection",
                        related_name="collections",
                        to="gestionTemplate.plasmide",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plasmid_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="plasmid_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="gestionTemplate.plasmidcollection",
            ),
        ),
    ]
