# Generated by Django 5.2.9 on 2026-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='plasmid_archive',
            field=models.FileField(null=True, upload_to='simulations/plasmid_archive/'),
        ),
    ]
