# Generated by Django 5.2.9 on 2026-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0002_anonymoustemplate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousTemplate',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='concentration_file',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='mapping_file',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='plasmids_zip',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='primers_file',
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Nom d'affichage"),
        ),
    ]
