# Generated by Django 5.2.9 on 2026-02-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0003_publicationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationrequest',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTemplate.campaign'),
        ),
    ]
