# Generated by Django 5.2.9 on 2026-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0003_campaign_plasmid_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='file',
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='structure',
            field=models.JSONField(default=dict, verbose_name='Structure du Template'),
        ),
    ]
