# Generated by Django 5.2.9 on 2026-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0004_alter_publicationrequest_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
