# Generated by Django 5.2.9 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0006_remove_correspondancetable_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public ?'),
        ),
    ]
