# Generated by Django 5.2.9 on 2026-02-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0008_tablepublicationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_requests', to='gestionTemplate.mappingtemplate'),
        ),
        migrations.AlterField(
            model_name='publicationrequest',
            name='plasmid_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='TablePublicationRequest',
        ),
    ]
