# Generated by Django 5.2.9 on 2026-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0010_campaigntemplate_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmidcollection',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public ?'),
        ),
    ]
