# Generated by Django 5.2.9 on 2026-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0011_plasmidcollection_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom du fichier de correspondance'),
        ),
    ]
