# Generated by Django 5.2.9 on 2026-02-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTemplate', '0012_alter_mappingtemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTemplate.plasmidcollection'),
        ),
    ]
